baseURL = 'https://gastonotero.com/'
languageCode = 'en-us'
title = 'Gaston Otero'

theme = 'not-much'


# Navigation
[menu]
    [[menu.main]]
    identifier = "about"
    name = "about"
    title = "About"
    url = "/"
    weight = 1

    [[menu.main]]
    identifier = "blog"
    name = "blog"
    title = "blog"
    url = "/blog"
    weight = 2

    [[menu.main]]
    identifier = "projects"
    name = "projects"
    title = "projects"
    url = "/projects"
    weight = 3

# Styles
[params]
    theme = "dark"
    palette = "custom-palette"
    copyright = "© {year}"
